package com.matchimban.matchimban_api.notification.entity;

public enum NotificationType {
    CHAT_MESSAGE,
    MEETING_MEMBER_JOINED,
    VOTE_ROUND1_OPEN,
    VOTE_ROUND2_OPEN,
    VOTE_RESULT_READY,
    FINAL_SELECTION_CONFIRMED,
    SETTLEMENT_SELECTION_OPEN,
    SETTLEMENT_RESULT_READY,
    SETTLEMENT_PAYMENT_REQUESTED,
    SETTLEMENT_PAYMENT_CONFIRMED,
    SETTLEMENT_UNPAID_REMIND,
    SETTLEMENT_BULK_DONE,
    REVIEW_REQUEST
}
