CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    noti_type VARCHAR(40) NOT NULL,
    title VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NULL,
    sub_target_id BIGINT NULL,
    deeplink_path VARCHAR(255) NULL,
    payload_json JSONB NULL,
    event_key VARCHAR(120) NOT NULL,
    read_at TIMESTAMPTZ NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_notifications_member
        FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT uq_notifications_member_event_key
        UNIQUE (member_id, event_key),
    CONSTRAINT ck_notifications_title_length
        CHECK (char_length(title) <= 50)
);

CREATE INDEX idx_notifications_member_feed
    ON notifications (member_id, is_deleted, created_at DESC, id DESC);

CREATE INDEX idx_notifications_member_unread
    ON notifications (member_id, is_deleted, read_at, created_at DESC, id DESC);

CREATE INDEX idx_notifications_retention
    ON notifications (created_at);

DROP TRIGGER IF EXISTS trg_notifications_set_updated_at ON notifications;
CREATE TRIGGER trg_notifications_set_updated_at
    BEFORE UPDATE ON notifications
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
