CREATE TABLE notification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    fcm_token TEXT NOT NULL,
    device_key VARCHAR(120) NULL,
    user_agent VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_notification_tokens_member
        FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT uq_notification_tokens_fcm_token
        UNIQUE (fcm_token)
);

CREATE INDEX idx_notification_tokens_member_active_updated
    ON notification_tokens (member_id, is_active, updated_at DESC);

CREATE INDEX idx_notification_tokens_device_key
    ON notification_tokens (device_key);

DROP TRIGGER IF EXISTS trg_notification_tokens_set_updated_at ON notification_tokens;
CREATE TRIGGER trg_notification_tokens_set_updated_at
    BEFORE UPDATE ON notification_tokens
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
