CREATE TABLE notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    notification_token_id BIGINT NULL,
    token_snapshot TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_at TIMESTAMPTZ NULL,
    worker_id VARCHAR(64) NULL,
    last_error_code VARCHAR(80) NULL,
    last_error_message TEXT NULL,
    sent_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_notification_outbox_notification
        FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_outbox_member
        FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_outbox_token
        FOREIGN KEY (notification_token_id) REFERENCES notification_tokens(id) ON DELETE SET NULL,
    CONSTRAINT ck_notification_outbox_status
        CHECK (status IN ('PENDING', 'IN_PROGRESS', 'SENT', 'FAILED', 'DEAD'))
);

CREATE INDEX idx_outbox_dispatch
    ON notification_outbox (status, next_attempt_at, id);

CREATE INDEX idx_outbox_notification
    ON notification_outbox (notification_id);

CREATE INDEX idx_outbox_in_progress
    ON notification_outbox (status, locked_at);

DROP TRIGGER IF EXISTS trg_notification_outbox_set_updated_at ON notification_outbox;
CREATE TRIGGER trg_notification_outbox_set_updated_at
    BEFORE UPDATE ON notification_outbox
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
