CREATE TABLE notification_schedule_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type VARCHAR(40) NOT NULL,
    member_id BIGINT NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    run_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    job_key VARCHAR(120) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    locked_at TIMESTAMPTZ NULL,
    worker_id VARCHAR(64) NULL,
    last_error_message TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_notification_schedule_jobs_member_job_key
        UNIQUE (member_id, job_key),
    CONSTRAINT fk_notification_schedule_jobs_member
        FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT ck_notification_schedule_jobs_status
        CHECK (status IN ('PENDING', 'IN_PROGRESS', 'DONE', 'FAILED', 'DEAD'))
);

CREATE INDEX idx_schedule_dispatch
    ON notification_schedule_jobs (status, run_at, next_attempt_at, id);

CREATE INDEX idx_schedule_member
    ON notification_schedule_jobs (member_id, status, run_at);

CREATE INDEX idx_schedule_in_progress
    ON notification_schedule_jobs (status, locked_at);

DROP TRIGGER IF EXISTS trg_notification_schedule_jobs_set_updated_at ON notification_schedule_jobs;
CREATE TRIGGER trg_notification_schedule_jobs_set_updated_at
    BEFORE UPDATE ON notification_schedule_jobs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
